services:
  client:
    build: 
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "8001:8001"
    command: "python -m http.server 8001 --bind 0.0.0.0"

  server:
    build: 
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8000:8000"
    command: "flask run --port=8000 --host=0.0.0.0"